name: Test

on:
  push:
    branches:
    - main
  workflow_dispatch:
     
jobs:
  test:
    name: Run demo tests
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Run api tests
      run: mvn clean  test -Dcucumber.reporting.skip="true" -Dcucumber.filter.tags="@petstore"
      shell: cmd
        
    - name: Run web tests with Chrome
      run: mvn clean  test -Dcucumber.reporting.skip="true" -Dcucumber.filter.tags="@demoqa" -Dbrowser="chrome"
      shell: cmd
        
    - name: Run web tests with Firefox
      run: mvn clean test -Dcucumber.reporting.skip="true" -Dcucumber.filter.tags="@demoqa" -Dbrowser="firefox"
      shell: cmd
        
    - name: Run web tests with Edge
      run: mvn clean test -Dcucumber.reporting.skip="true" -Dcucumber.filter.tags="@demoqa" -Dbrowser="edge"
      shell: cmd
